apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      nodeSelector:
        role: teamcity
      containers:
      - name: teamcity
        image: jetbrains/teamcity-server:latest
        ports:
        - containerPort: 8111
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "3Gi"
            cpu: "1500m"
            ephemeral-storage: "7Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-nodeport
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
    - port: 80
      targetPort: 8111
      nodePort: 30070
