all:
  hosts:
    node1:
      ansible_host: 46.21.247.197
      ip: 192.168.10.250
      access_ip: 46.21.247.197
    node2:
      ansible_host: 51.250.86.233
      ip: 192.168.20.251
      access_ip: 51.250.86.233
    node3:
      ansible_host: 84.252.139.5
      ip: 192.168.30.252
      access_ip: 84.252.139.5
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
