server:
  service:
    type: NodePort
    nodePort: 30900
alertmanager:
  service:
    type: NodePort
    nodePort: 30903
pushgateway:
  service:
    type: NodePort
    nodePort: 30902
grafana:
  service:
    type: NodePort
    nodePort: 30080
  adminPassword: "password"
ingress:
  enabled: false
